services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.

    App\Service\Event\GenerateEntityEvent: ~

    App\Service\Interfaces\GenerateEntityEventInterface: '@App\Service\Event\GenerateEntityEvent'