services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.

    App\Service\Serializer\SerializerManager:
        tags:
            - { name: 'app.handler.serializer', key: 'handler_serializer' }

    App\Service\Serializer\SerializerNormalizeManager:
        tags:
            - { name: 'app.handler.serializer', key: 'handler_serializer_normalizer' }

    App\Service\Serializer\EntityHandler:
        arguments: [ !tagged_locator { tag: 'app.handler.serializer', index_by: 'key' } ]

    App\Service\Interfaces\EntityHandlerInterface: '@App\Service\Serializer\EntityHandler'

    App\Serializer\EmployeeNormalizer:
        tags: [ 'serializer.normalizer' ]

    App\Serializer\YouweTeamNormalizer:
        tags: [ 'serializer.normalizer' ]

    App\Service\Serializer\CustomObjectNormalizer: ~

    App\Service\Interfaces\CustomObjectNormalizerInterface: '@App\Service\Serializer\CustomObjectNormalizer'

    App\Service\Serializer\SnakeCaseToCamelCaseHandler: ~

    App\Service\Interfaces\SnakeCaseToCamelCaseHandlerInterface: '@App\Service\Serializer\SnakeCaseToCamelCaseHandler'

    Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter: '@serializer.name_converter.camel_case_to_snake_case'

    Symfony\Component\Serializer\Normalizer\NormalizerInterface $employeeNormalizer: '@App\Serializer\EmployeeNormalizer'

    Symfony\Component\Serializer\Normalizer\NormalizerInterface $youweTeamNormalizer: '@App\Serializer\YouweTeamNormalizer'