services:
    _defaults:
        autowire: true

    app.exception.listener:
        class: App\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
