version: "3"

services:
    db:
        image: mysql:8.0.20
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "./mysql:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
        networks:
            - symfony
    php:
        build:
            context: php
        volumes:
            - .:/var/www/html:ro
        networks:
            - symfony
    nginx:
        build:
            context: nginx
        volumes:
            - "./app:/var/www/symfony/"
        ports:
            - "80:80"
        networks:
            - symfony

volumes:
    db_app:

networks:
    symfony:
